version: '3.9'

services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: fitify_user
      POSTGRES_PASSWORD: fitify_pass
      POSTGRES_DB: fitify_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    # This healthcheck tells Docker to wait until Postgres is truly ready
    # before allowing the backend to connect.
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fitify_user -d fitify_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    command: uvicorn app.main:app --host 0.0.0.0 --reload
    volumes:
      - ./backend/app:/code/app
    environment:
      - DATABASE_URL=postgresql+asyncpg://fitify_user:fitify_pass@db:5432/fitify_db
    # This now waits for the 'db' service to be 'healthy', not just 'started'.
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '8000:8000'

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - '5173:5173'
    environment:
      - VITE_API_URL=http://localhost:8000/api
    depends_on:
      - backend

volumes:
  db_data:
